title: VirtualStaticVoid
tagline: 'Making sense of the ever changing'
description: 'A personal project showcase and blog on adventures in programming.'

author:
  name: 'Chris Stefano'
  email: virtualstaticvoid@gmail.com
  github: github.com/virtualstaticvoid

url: https://www.virtualstaticvoid.com

highlighter: rouge
permalink: pretty

paginate: 5

plugins:
  - jekyll-paginate
